/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/agenda` | `/agenda`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/pets` | `/pets`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/servicos` | `/servicos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/tutores` | `/tutores`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/agenda` | `/agenda`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/pets` | `/pets`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/servicos` | `/servicos`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/tutores` | `/tutores`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/agenda${`?${string}` | `#${string}` | ''}` | `/agenda${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(main)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/pets${`?${string}` | `#${string}` | ''}` | `/pets${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/servicos${`?${string}` | `#${string}` | ''}` | `/servicos${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/tutores${`?${string}` | `#${string}` | ''}` | `/tutores${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/agenda` | `/agenda`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/pets` | `/pets`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/servicos` | `/servicos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/tutores` | `/tutores`; params?: Router.UnknownInputParams; };
    }
  }
}
